

CREATE MATERIALIZED VIEW vw_train_alarm_info 
WITH (timescaledb.continuous) AS 
 SELECT max(pro_macda.msg_calc_train_no) AS train_no,
    pro_macda.msg_calc_dvc_no AS carriage_no,
	time_bucket('2 min', pro_macda.msg_calc_dvc_time) AS alarm_time,
    last(pro_macda.bocflt_ef_u11, pro_macda.msg_calc_dvc_time) AS bocflt_ef_u11,
    last(pro_macda.bocflt_ef_u12, pro_macda.msg_calc_dvc_time) AS bocflt_ef_u12,
    last(pro_macda.bocflt_cf_u11, pro_macda.msg_calc_dvc_time) AS bocflt_cf_u11,
    last(pro_macda.bocflt_cf_u12, pro_macda.msg_calc_dvc_time) AS bocflt_cf_u12,
    last(pro_macda.bflt_vfd_u11, pro_macda.msg_calc_dvc_time) AS bflt_vfd_u11,
    last(pro_macda.bflt_vfd_com_u11, pro_macda.msg_calc_dvc_time) AS bflt_vfd_com_u11,
    last(pro_macda.bflt_vfd_u12, pro_macda.msg_calc_dvc_time) AS bflt_vfd_u12,
    last(pro_macda.bflt_vfd_com_u12, pro_macda.msg_calc_dvc_time) AS bflt_vfd_com_u12,
    last(pro_macda.blpflt_comp_u11, pro_macda.msg_calc_dvc_time) AS blpflt_comp_u11,
    last(pro_macda.bscflt_comp_u11, pro_macda.msg_calc_dvc_time) AS bscflt_comp_u11,
    last(pro_macda.bscflt_vent_u11, pro_macda.msg_calc_dvc_time) AS bscflt_vent_u11,
    last(pro_macda.blpflt_comp_u12, pro_macda.msg_calc_dvc_time) AS blpflt_comp_u12,
    last(pro_macda.bscflt_comp_u12, pro_macda.msg_calc_dvc_time) AS bscflt_comp_u12,
    last(pro_macda.bscflt_vent_u12, pro_macda.msg_calc_dvc_time) AS bscflt_vent_u12,
    last(pro_macda.bflt_fad_u11, pro_macda.msg_calc_dvc_time) AS bflt_fad_u11,
    last(pro_macda.bflt_fad_u12, pro_macda.msg_calc_dvc_time) AS bflt_fad_u12,
    last(pro_macda.bflt_rad_u11, pro_macda.msg_calc_dvc_time) AS bflt_rad_u11,
    last(pro_macda.bflt_rad_u12, pro_macda.msg_calc_dvc_time) AS bflt_rad_u12,
    last(pro_macda.bflt_ap_u11, pro_macda.msg_calc_dvc_time) AS bflt_ap_u11,
    last(pro_macda.bflt_expboard_u1, pro_macda.msg_calc_dvc_time) AS bflt_expboard_u1,
    last(pro_macda.bflt_frstemp_u1, pro_macda.msg_calc_dvc_time) AS bflt_frstemp_u1,
    last(pro_macda.bflt_rnttemp_u1, pro_macda.msg_calc_dvc_time) AS bflt_rnttemp_u1,
    last(pro_macda.bflt_splytemp_u11, pro_macda.msg_calc_dvc_time) AS bflt_splytemp_u11,
    last(pro_macda.bflt_splytemp_u12, pro_macda.msg_calc_dvc_time) AS bflt_splytemp_u12,
    last(pro_macda.bflt_coiltemp_u11, pro_macda.msg_calc_dvc_time) AS bflt_coiltemp_u11,
    last(pro_macda.bflt_coiltemp_u12, pro_macda.msg_calc_dvc_time) AS bflt_coiltemp_u12,
    last(pro_macda.bflt_insptemp_u11, pro_macda.msg_calc_dvc_time) AS bflt_insptemp_u11,
    last(pro_macda.bflt_insptemp_u12, pro_macda.msg_calc_dvc_time) AS bflt_insptemp_u12,
    last(pro_macda.bflt_lowpres_u11, pro_macda.msg_calc_dvc_time) AS bflt_lowpres_u11,
    last(pro_macda.bflt_lowpres_u12, pro_macda.msg_calc_dvc_time) AS bflt_lowpres_u12,
    last(pro_macda.bflt_highpres_u11, pro_macda.msg_calc_dvc_time) AS bflt_highpres_u11,
    last(pro_macda.bflt_highpres_u12, pro_macda.msg_calc_dvc_time) AS bflt_highpres_u12,
    last(pro_macda.bflt_diffpres_u1, pro_macda.msg_calc_dvc_time) AS bflt_diffpres_u1,
    last(pro_macda.bocflt_ef_u21, pro_macda.msg_calc_dvc_time) AS bocflt_ef_u21,
    last(pro_macda.bocflt_ef_u22, pro_macda.msg_calc_dvc_time) AS bocflt_ef_u22,
    last(pro_macda.bocflt_cf_u21, pro_macda.msg_calc_dvc_time) AS bocflt_cf_u21,
    last(pro_macda.bocflt_cf_u22, pro_macda.msg_calc_dvc_time) AS bocflt_cf_u22,
    last(pro_macda.bflt_vfd_u21, pro_macda.msg_calc_dvc_time) AS bflt_vfd_u21,
    last(pro_macda.bflt_vfd_com_u21, pro_macda.msg_calc_dvc_time) AS bflt_vfd_com_u21,
    last(pro_macda.bflt_vfd_u22, pro_macda.msg_calc_dvc_time) AS bflt_vfd_u22,
    last(pro_macda.bflt_vfd_com_u22, pro_macda.msg_calc_dvc_time) AS bflt_vfd_com_u22,
    last(pro_macda.blpflt_comp_u21, pro_macda.msg_calc_dvc_time) AS blpflt_comp_u21,
    last(pro_macda.bscflt_comp_u21, pro_macda.msg_calc_dvc_time) AS bscflt_comp_u21,
    last(pro_macda.bscflt_vent_u21, pro_macda.msg_calc_dvc_time) AS bscflt_vent_u21,
    last(pro_macda.blpflt_comp_u22, pro_macda.msg_calc_dvc_time) AS blpflt_comp_u22,
    last(pro_macda.bscflt_comp_u22, pro_macda.msg_calc_dvc_time) AS bscflt_comp_u22,
    last(pro_macda.bscflt_vent_u22, pro_macda.msg_calc_dvc_time) AS bscflt_vent_u22,
    last(pro_macda.bflt_fad_u21, pro_macda.msg_calc_dvc_time) AS bflt_fad_u21,
    last(pro_macda.bflt_fad_u22, pro_macda.msg_calc_dvc_time) AS bflt_fad_u22,
    last(pro_macda.bflt_rad_u21, pro_macda.msg_calc_dvc_time) AS bflt_rad_u21,
    last(pro_macda.bflt_rad_u22, pro_macda.msg_calc_dvc_time) AS bflt_rad_u22,
    last(pro_macda.bflt_ap_u21, pro_macda.msg_calc_dvc_time) AS bflt_ap_u21,
    last(pro_macda.bflt_expboard_u2, pro_macda.msg_calc_dvc_time) AS bflt_expboard_u2,
    last(pro_macda.bflt_frstemp_u2, pro_macda.msg_calc_dvc_time) AS bflt_frstemp_u2,
    last(pro_macda.bflt_rnttemp_u2, pro_macda.msg_calc_dvc_time) AS bflt_rnttemp_u2,
    last(pro_macda.bflt_splytemp_u21, pro_macda.msg_calc_dvc_time) AS bflt_splytemp_u21,
    last(pro_macda.bflt_splytemp_u22, pro_macda.msg_calc_dvc_time) AS bflt_splytemp_u22,
    last(pro_macda.bflt_coiltemp_u21, pro_macda.msg_calc_dvc_time) AS bflt_coiltemp_u21,
    last(pro_macda.bflt_coiltemp_u22, pro_macda.msg_calc_dvc_time) AS bflt_coiltemp_u22,
    last(pro_macda.bflt_insptemp_u21, pro_macda.msg_calc_dvc_time) AS bflt_insptemp_u21,
    last(pro_macda.bflt_insptemp_u22, pro_macda.msg_calc_dvc_time) AS bflt_insptemp_u22,
    last(pro_macda.bflt_lowpres_u21, pro_macda.msg_calc_dvc_time) AS bflt_lowpres_u21,
    last(pro_macda.bflt_lowpres_u22, pro_macda.msg_calc_dvc_time) AS bflt_lowpres_u22,
    last(pro_macda.bflt_highpres_u21, pro_macda.msg_calc_dvc_time) AS bflt_highpres_u21,
    last(pro_macda.bflt_highpres_u22, pro_macda.msg_calc_dvc_time) AS bflt_highpres_u22,
    last(pro_macda.bflt_diffpres_u2, pro_macda.msg_calc_dvc_time) AS bflt_diffpres_u2,
    last(pro_macda.bflt_emergivt, pro_macda.msg_calc_dvc_time) AS bflt_emergivt,
    last(pro_macda.bflt_vehtemp_u1, pro_macda.msg_calc_dvc_time) AS bflt_vehtemp_u1,
    last(pro_macda.bflt_vehtemp_u2, pro_macda.msg_calc_dvc_time) AS bflt_vehtemp_u2,
    last(pro_macda.bflt_airmon_u1, pro_macda.msg_calc_dvc_time) AS bflt_airmon_u1,
    last(pro_macda.bflt_airmon_u2, pro_macda.msg_calc_dvc_time) AS bflt_airmon_u2,
    last(pro_macda.bflt_currentmon, pro_macda.msg_calc_dvc_time) AS bflt_currentmon,
    last(pro_macda.bflt_tcms, pro_macda.msg_calc_dvc_time) AS bflt_tcms,
    last(pro_macda.bflt_tempover, pro_macda.msg_calc_dvc_time) AS bflt_tempover,
    last(pro_macda.bflt_powersupply_u1, pro_macda.msg_calc_dvc_time) AS bflt_powersupply_u1,
    last(pro_macda.bflt_powersupply_u2, pro_macda.msg_calc_dvc_time) AS bflt_powersupply_u2,
    last(pro_macda.bflt_exhaustfan, pro_macda.msg_calc_dvc_time) AS bflt_exhaustfan,
    last(pro_macda.bflt_exhaustval, pro_macda.msg_calc_dvc_time) AS bflt_exhaustval,
    '通风机过流故障U1-1'::text AS bocflt_ef_u11_name,
    '通风机过流故障U1-2'::text AS bocflt_ef_u12_name,
    '冷凝风机过流故障U1-1'::text AS bocflt_cf_u11_name,
    '冷凝风机过流故障U1-2'::text AS bocflt_cf_u12_name,
    '变频器保护故障U1-1'::text AS bflt_vfd_u11_name,
    '变频器通讯故障U1-1'::text AS bflt_vfd_com_u11_name,
    '变频器保护故障U1-2'::text AS bflt_vfd_u12_name,
    '变频器通讯故障U1-2'::text AS bflt_vfd_com_u12_name,
    '低压故障U1-1'::text AS blpflt_comp_u11_name,
    '高压故障U1-1'::text AS bscflt_comp_u11_name,
    '排气故障U1-1'::text AS bscflt_vent_u11_name,
    '低压故障U1-2'::text AS blpflt_comp_u12_name,
    '高压故障U1-2'::text AS bscflt_comp_u12_name,
    '排气故障U1-2'::text AS bscflt_vent_u12_name,
    '新风阀故障U1-1'::text AS bflt_fad_u11_name,
    '新风阀故障U1-2'::text AS bflt_fad_u12_name,
    '回风阀故障U1-1'::text AS bflt_rad_u11_name,
    '回风阀故障U1-2'::text AS bflt_rad_u12_name,
    '空气净化器故障U1-1'::text AS bflt_ap_u11_name,
    '扩展模块通讯故障U1'::text AS bflt_expboard_u1_name,
    '新风温度传感器故障U1'::text AS bflt_frstemp_u1_name,
    '回风温度传感器故障U1'::text AS bflt_rnttemp_u1_name,
    '送风温度传感器故障U1-1'::text AS bflt_splytemp_u11_name,
    '送风温度传感器故障U1-2'::text AS bflt_splytemp_u12_name,
    '盘管温度传感器故障U1-1'::text AS bflt_coiltemp_u11_name,
    '盘管温度传感器故障U1-2'::text AS bflt_coiltemp_u12_name,
    '吸气温度传感器故障U1-1'::text AS bflt_insptemp_u11_name,
    '吸气温度传感器故障U1-2'::text AS bflt_insptemp_u12_name,
    '低压压力传感器故障U1-1'::text AS bflt_lowpres_u11_name,
    '低压压力传感器故障U1-2'::text AS bflt_lowpres_u12_name,
    '高压压力传感器故障U1-1'::text AS bflt_highpres_u11_name,
    '高压压力传感器故障U1-2'::text AS bflt_highpres_u12_name,
    '压差传感器故障U1'::text AS bflt_diffpres_u1_name,
    '通风机过流故障U2-1'::text AS bocflt_ef_u21_name,
    '通风机过流故障U2-2'::text AS bocflt_ef_u22_name,
    '冷凝风机过流故障U2-1'::text AS bocflt_cf_u21_name,
    '冷凝风机过流故障U2-2'::text AS bocflt_cf_u22_name,
    '变频器保护故障U2-1'::text AS bflt_vfd_u21_name,
    '变频器通讯故障U2-1'::text AS bflt_vfd_com_u21_name,
    '变频器保护故障U2-2'::text AS bflt_vfd_u22_name,
    '变频器通讯故障U2-2'::text AS bflt_vfd_com_u22_name,
    '低压故障U2-1'::text AS blpflt_comp_u21_name,
    '高压故障U2-1'::text AS bscflt_comp_u21_name,
    '排气故障U2-1'::text AS bscflt_vent_u21_name,
    '低压故障U2-2'::text AS blpflt_comp_u22_name,
    '高压故障U2-2'::text AS bscflt_comp_u22_name,
    '排气故障U2-2'::text AS bscflt_vent_u22_name,
    '新风阀故障U2-1'::text AS bflt_fad_u21_name,
    '新风阀故障U2-2'::text AS bflt_fad_u22_name,
    '回风阀故障U2-1'::text AS bflt_rad_u21_name,
    '回风阀故障U2-2'::text AS bflt_rad_u22_name,
    '空气净化器故障U2-1'::text AS bflt_ap_u21_name,
    '扩展模块通讯故障U2'::text AS bflt_expboard_u2_name,
    '新风温度传感器故障U2'::text AS bflt_frstemp_u2_name,
    '回风温度传感器故障U2'::text AS bflt_rnttemp_u2_name,
    '送风温度传感器故障U2-1'::text AS bflt_splytemp_u21_name,
    '送风温度传感器故障U2-2'::text AS bflt_splytemp_u22_name,
    '盘管温度传感器故障U2-1'::text AS bflt_coiltemp_u21_name,
    '盘管温度传感器故障U2-2'::text AS bflt_coiltemp_u22_name,
    '吸气温度传感器故障U2-1'::text AS bflt_insptemp_u21_name,
    '吸气温度传感器故障U2-2'::text AS bflt_insptemp_u22_name,
    '低压压力传感器故障U2-1'::text AS bflt_lowpres_u21_name,
    '低压压力传感器故障U2-2'::text AS bflt_lowpres_u22_name,
    '高压压力传感器故障U2-1'::text AS bflt_highpres_u21_name,
    '高压压力传感器故障U2-2'::text AS bflt_highpres_u22_name,
    '压差传感器故障U2'::text AS bflt_diffpres_u2_name,
    '紧急逆变器故障'::text AS bflt_emergivt_name,
    '车厢温度传感器1故障'::text AS bflt_vehtemp_u1_name,
    '车厢温度传感器2故障'::text AS bflt_vehtemp_u2_name,
    '机组1空气监测终端通讯故障'::text AS bflt_airmon_u1_name,
    '机组2空气监测终端通讯故障'::text AS bflt_airmon_u2_name,
    '电流监测单元通讯故障'::text AS bflt_currentmon_name,
    'TCMS通讯故障'::text AS bflt_tcms_name,
    '车厢温度超温预警'::text AS bflt_tempover_name,
    '供电故障-U1'::text AS bflt_powersupply_u1_name,
    '供电故障-U2'::text AS bflt_powersupply_u2_name,
    '废排风机故障'::text AS bflt_exhaustfan_name,
    '废排风阀故障'::text AS bflt_exhaustval_name
   FROM pro_macda
  WHERE pro_macda.msg_calc_dvc_time >= (now() - '2 minute'::interval) and msg_calc_train_no <> '00000'
  GROUP BY time_bucket('2 min', pro_macda.msg_calc_dvc_time), pro_macda.msg_calc_dvc_no;
  
SELECT add_continuous_aggregate_policy('vw_train_alarm_info'::regclass, start_offset=>NULL, end_offset=>'2 mins'::interval,  schedule_interval=>'1 mins'::interval);
  
  