-- 创建表：sys_fields
CREATE TABLE IF NOT EXISTS sys_fields (
    field_name VARCHAR(255),
    field_code VARCHAR(255) UNIQUE,
    field_category VARCHAR(255)
);

-- 插入数据
INSERT INTO sys_fields (field_name, field_code, field_category) VALUES
('Flag', 'dvc_flag', 'basic'),
('车辆编码', 'dvc_train_no', 'basic'),
('车厢号', 'dvc_carriage_no', 'basic'),
('年', 'dvc_year', 'basic'),
('月', 'dvc_month', 'basic'),
('日', 'dvc_day', 'Basic'),
('时', 'dvc_hour', 'Basic'),
('分', 'dvc_minute', 'Basic'),
('秒', 'dvc_second', 'Basic'),
('通风机运行U1-1', 'cFBK_EF_U11', 'Status'),
('冷凝风机运行U1-1', 'cFBK_CF_U11', 'Status'),
('冷凝风机运行U1-2', 'cFBK_CF_U12', 'Status'),
('压缩机运行U11', 'cFBK_Comp_U11', 'Status'),
('压缩机运行U12', 'cFBK_Comp_U12', 'Status'),
('空气净化运行U1-1', 'cFBK_AP_U11', 'Status'),
('空气净化运行U1-2', 'cFBK_AP_U12', 'Status'),
('通风机运行U2-1', 'cFBK_EF_U21', 'Status'),
('冷凝风机运行U2-1', 'cFBK_CF_U21', 'Status'),
('冷凝风机运行U2-2', 'cFBK_CF_U22', 'Status'),
('压缩机运行U21', 'cFBK_Comp_U21', 'Status'),
('压缩机运行U22', 'cFBK_Comp_U22', 'Status'),
('空气净化运行U2-1', 'cFBK_AP_U21', 'Status'),
('空气净化运行U2-2', 'cFBK_AP_U22', 'Status'),
('机组1三相电源状态', 'cFBK_TPP_U1', 'Status'),
('机组2三相电源状态', 'cFBK_TPP_U2', 'Status'),
('紧急通风运行U1', 'cFBK_EV_U1', 'Status'),
('紧急通风运行U2', 'cFBK_EV_U2', 'Status'),
('通风机过流故障U1-1', 'bOCFlt_EF_U11', 'Error'),
('通风机过流故障U1-2', 'bOCFlt_EF_U12', 'Error'),
('冷凝风机过流故障U1-1', 'bOCFlt_CF_U11', 'Error'),
('冷凝风机过流故障U1-2', 'bOCFlt_CF_U12', 'Error'),
('变频器保护故障U1-1', 'bFlt_VFD_U11', 'Error'),
('变频器通讯故障U1-1', 'bFlt_VFD_COM_U11', 'Error'),
('变频器保护故障U1-2', 'bFlt_VFD_U12', 'Error'),
('变频器通讯故障U1-2', 'bFlt_VFD_COM_U12', 'Error'),
('低压故障U1-1', 'bLPFlt_Comp_U11', 'Error'),
('高压故障U1-1', 'bSCFlt_Comp_U11', 'Error'),
('排气故障U1-1', 'bSCFlt_Vent_U11', 'Error'),
('低压故障U1-2', 'bLPFlt_Comp_U12', 'Error'),
('高压故障U1-2', 'bSCFlt_Comp_U12', 'Error'),
('排气故障U1-2', 'bSCFlt_Vent_U12', 'Error'),
('新风阀故障U1-1', 'bFlt_FAD_U11', 'Error'),
('新风阀故障U1-2', 'bFlt_FAD_U12', 'Error'),
('新风阀故障U1-3', 'bFlt_FAD_U13', 'Error'),
('新风阀故障U1-4', 'bFlt_FAD_U14', 'Error'),
('回风阀故障U1-1', 'bFlt_RAD_U11', 'Error'),
('回风阀故障U1-2', 'bFlt_RAD_U12', 'Error'),
('回风阀故障U1-3', 'bFlt_RAD_U13', 'Error'),
('回风阀故障U1-4', 'bFlt_RAD_U14', 'Error'),
('空气净化器故障U1-1', 'bFlt_AP_U11', 'Error'),
('空气净化器故障U1-2', 'bFlt_AP_U12', 'Error'),
('扩展模块通讯故障U1', 'bFlt_ExpBoard_U1', 'Error'),
('新风温度传感器故障U1', 'bFlt_FrsTemp_U1', 'Error'),
('回风温度传感器故障U1', 'bFlt_RntTemp_U1', 'Error'),
('送风温度传感器故障U1-1', 'bFlt_SplyTemp_U11', 'Error'),
('送风温度传感器故障U1-2', 'bFlt_SplyTemp_U12', 'Error'),
('吸气温度传感器故障U1-1', 'bFlt_InspTemp_U11', 'Error'),
('吸气温度传感器故障U1-2', 'bFlt_InspTemp_U12', 'Error'),
('低压压力传感器故障U1-1', 'bFlt_LowPres_U11', 'Error'),
('低压压力传感器故障U1-2', 'bFlt_LowPres_U12', 'Error'),
('高压压力传感器故障U1-1', 'bFlt_HighPres_U11', 'Error'),
('高压压力传感器故障U1-2', 'bFlt_HighPres_U12', 'Error'),
('压差传感器故障U1', 'bFlt_DiffPres_U1', 'Error'),
('通风机过流故障U2-1', 'bOCFlt_EF_U21', 'Error'),
('通风机过流故障U2-2', 'bOCFlt_EF_U22', 'Error'),
('冷凝风机过流故障U2-1', 'bOCFlt_CF_U21', 'Error'),
('冷凝风机过流故障U2-2', 'bOCFlt_CF_U22', 'Error'),
('变频器保护故障U2-1', 'bFlt_VFD_U21', 'Error'),
('变频器通讯故障U2-1', 'bFlt_VFD_COM_U21', 'Error'),
('变频器保护故障U2-2', 'bFlt_VFD_U22', 'Error'),
('变频器通讯故障U2-2', 'bFlt_VFD_COM_U22', 'Error'),
('低压故障U2-1', 'bLPFlt_Comp_U21', 'Error'),
('高压故障U2-1', 'bSCFlt_Comp_U21', 'Error'),
('排气故障U2-1', 'bSCFlt_Vent_U21', 'Error'),
('低压故障U2-2', 'bLPFlt_Comp_U22', 'Error'),
('高压故障U2-2', 'bSCFlt_Comp_U22', 'Error'),
('排气故障U2-2', 'bSCFlt_Vent_U22', 'Error'),
('新风阀故障U2-1', 'bFlt_FAD_U21', 'Error'),
('新风阀故障U2-2', 'bFlt_FAD_U22', 'Error'),
('新风阀故障U2-3', 'bFlt_FAD_U23', 'Error'),
('新风阀故障U2-4', 'bFlt_FAD_U24', 'Error'),
('回风阀故障U2-1', 'bFlt_RAD_U21', 'Error'),
('回风阀故障U2-2', 'bFlt_RAD_U22', 'Error'),
('回风阀故障U2-3', 'bFlt_RAD_U23', 'Error'),
('回风阀故障U2-4', 'bFlt_RAD_U24', 'Error'),
('空气净化器故障U2-1', 'bFlt_AP_U21', 'Error'),
('空气净化器故障U2-2', 'bFlt_AP_U22', 'Error'),
('扩展模块通讯故障U2', 'bFlt_ExpBoard_U2', 'Error'),
('新风温度传感器故障U2', 'bFlt_FrsTemp_U2', 'Error'),
('回风温度传感器故障U2', 'bFlt_RntTemp_U2', 'Error'),
('送风温度传感器故障U2-1', 'bFlt_SplyTemp_U21', 'Error'),
('送风温度传感器故障U2-2', 'bFlt_SplyTemp_U22', 'Error'),
('吸气温度传感器故障U2-1', 'bFlt_InspTemp_U21', 'Error'),
('吸气温度传感器故障U2-2', 'bFlt_InspTemp_U22', 'Error'),
('低压压力传感器故障U2-1', 'bFlt_LowPres_U21', 'Error'),
('低压压力传感器故障U2-2', 'bFlt_LowPres_U22', 'Error'),
('高压压力传感器故障U2-1', 'bFlt_HighPres_U21', 'Error'),
('高压压力传感器故障U2-2', 'bFlt_HighPres_U22', 'Error'),
('压差传感器故障U2', 'bFlt_DiffPres_U2', 'Error'),
('紧急逆变器故障', 'bFlt_EmergIVT', 'Error'),
('车厢温度传感器1故障', 'bFlt_VehTemp_U1', 'Error'),
('车厢湿度传感器1故障', 'bflt_VehHum_U1', 'Error'),
('车厢温度传感器2故障', 'bFlt_VehTemp_U2', 'Error'),
('车厢湿度传感器2故障', 'bflt_VehHum_U2', 'Error'),
('机组1空气监测终端通讯故障', 'bFlt_AirMon_U1', 'Error'),
('机组2空气监测终端通讯故障', 'bFlt_AirMon_U2', 'Error'),
('电流监测单元通讯故障', 'bFlt_CurrentMon', 'Error'),
('TCMS通讯故障', 'bFlt_TCMS', 'Error'),
('通风机短路故障U1', 'bSCFlt_EF_U1', 'Error'),
('冷凝风机短路故障U1', 'bSCFlt_CF_U1', 'Error'),
('变频器供电短路故障U1-1', 'bSCFlt_VFD_PW_U11', 'Error'),
('变频器供电短路故障U1-2', 'bSCFlt_VFD_PW_U12', 'Error'),
('通风机短路故障U2', 'bSCFlt_EF_U2', 'Error'),
('冷凝风机短路故障U2', 'bSCFlt_CF_U2', 'Error'),
('变频器供电短路故障U2-1', 'bSCFlt_VFD_PW_U21', 'Error'),
('变频器供电短路故障U2-2', 'bSCFlt_VFD_PW_U22', 'Error'),
('通风机接触器故障U1', 'bFlt_EF_CNT_U1', 'Error'),
('冷凝风机接触器故障U1-1', 'bFlt_CF_CNT_U11', 'Error'),
('冷凝风机接触器故障U1-2', 'bFlt_CF_CNT_U12', 'Error'),
('压缩机变频器接触器故障U1-1', 'bFlt_VFD_CNT_U11', 'Error'),
('压缩机变频器接触器故障U1-2', 'bFlt_VFD_CNT_U12', 'Error'),
('紧急通风接触器故障U1', 'bFlt__EV_CNT_U1', 'Error'),
('通风机接触器故障U2', 'bFlt_EF_CNT_U2', 'Error'),
('冷凝风机接触器故障U2-1', 'bFlt_CF_CNT_U21', 'Error'),
('冷凝风机接触器故障U2-2', 'bFlt_CF_CNT_U22', 'Error'),
('压缩机变频器接触器故障U2-1', 'bFlt_VFD_CNT_U21', 'Error'),
('压缩机变频器接触器故障U2-2', 'bFlt_VFD_CNT_U22', 'Error'),
('紧急通风接触器故障U2', 'bFlt__EV_CNT_U2', 'Error'),
('车厢温度超温预警', 'bFlt_TempOver', 'Error'),
('新风温度-系统', 'fas_sys', 'Param'),
('回风温度-系统', 'ras_sys', 'Param'),
('目标温度', 'tic', 'Param'),
('载客量', 'load', 'Param'),
('车厢温度-1', 'tVeh_1', 'Param'),
('车厢湿度-1', 'humdity_1', 'Param'),
('车厢温度-2', 'tVeh_2', 'Param'),
('车厢湿度-2', 'humdity_2', 'Param'),
('空气质量-温度-U1', 'AQ_t_u1', 'Param'),
('空气质量-湿度-U1', 'AQ_h_u1', 'Param'),
('空气质量-CO2-U1', 'AQ_CO2_u1', 'Param'),
('空气质量-TVOC-U1', 'AQ_TVOC_u1', 'Param'),
('空气质量-PM2.5-U1', 'AQ_PM2_5_u1', 'Param'),
('空气质量-PM10-U1', 'AQ_PM10_u1', 'Param'),
('空调运行模式U1', 'wMode_u1', 'Param'),
('压差-U1', 'presDiff_u1', 'Param'),
('新风温度-U1', 'fas_u1', 'Param'),
('回风温度-U1', 'ras_u1', 'Param'),
('新风阀开度-U1', 'fadpos_u1', 'Param'),
('回风阀开度-U1', 'radpos_u1', 'Param'),
('压缩机频率-U11', 'F_CP_u11', 'Param'),
('压缩机电流-U11', 'I_CP_u11', 'Param'),
('压缩机电压-U11', 'V_CP_u11', 'Param'),
('压缩机功率-U11', 'P_CP_u11', 'Param'),
('吸气温度-U11', 'suckT_u11', 'Param'),
('吸气压力-U11', 'suckP_u11', 'Param'),
('过热度-U11', 'sp_u11', 'Param'),
('电子膨胀阀开度-U11', 'eevpos_u11', 'Param'),
('高压压力-U11', 'highpress_u11', 'Param'),
('送风温度-U11', 'sas_u11', 'Param'),
('压缩机频率-U12', 'F_CP_u12', 'Param'),
('压缩机电流-U12', 'I_CP_u12', 'Param'),
('压缩机电压-U12', 'V_CP_u12', 'Param'),
('压缩机功率-U12', 'P_CP_u12', 'Param'),
('吸气温度-U12', 'suckT_u12', 'Param'),
('吸气压力-U12', 'suckP_u12', 'Param'),
('过热度-U12', 'sp_u12', 'Param'),
('电子膨胀阀开度-U12', 'eevpos_u12', 'Param'),
('高压压力-U12', 'highpress_u12', 'Param'),
('送风温度-U12', 'sas_u12', 'Param'),
('空气质量-温度-U2', 'AQ_t_u2', 'Param'),
('空气质量-湿度-U2', 'AQ_h_u2', 'Param'),
('空气质量-CO2-U2', 'AQ_CO2_u2', 'Param'),
('空气质量-TVOC-U2', 'AQ_TVOC_u2', 'Param'),
('空气质量-PM2.5-U2', 'AQ_PM2_5_u2', 'Param'),
('空气质量-PM10-U2', 'AQ_PM10_u2', 'Param'),
('空调运行模式U2', 'wMode_u2', 'Param'),
('压差-U2', 'presDiff_u2', 'Param'),
('新风温度-U2', 'fas_u2', 'Param'),
('回风温度-U2', 'ras_u2', 'Param'),
('新风阀开度-U2', 'fadpos_u2', 'Param'),
('回风阀开度-U2', 'radpos_u2', 'Param'),
('压缩机频率-U21', 'F_CP_u21', 'Param'),
('压缩机电流-U21', 'I_CP_u21', 'Param'),
('压缩机电压-U21', 'V_CP_u21', 'Param'),
('压缩机功率-U21', 'P_CP_u21', 'Param'),
('吸气温度-U21', 'suckT_u21', 'Param'),
('吸气压力-U21', 'suckP_u21', 'Param'),
('过热度-U21', 'sp_u21', 'Param'),
('电子膨胀阀开度-U21', 'eevpos_u21', 'Param'),
('高压压力-U21', 'highpress_u21', 'Param'),
('送风温度-U21', 'sas_u21', 'Param'),
('压缩机频率-U22', 'F_CP_u22', 'Param'),
('压缩机电流-U22', 'I_CP_u22', 'Param'),
('压缩机电压-U22', 'V_CP_u22', 'Param'),
('压缩机功率-U22', 'P_CP_u22', 'Param'),
('吸气温度-U22', 'suckT_u22', 'Param'),
('吸气压力-U22', 'suckP_u22', 'Param'),
('过热度-U22', 'sp_u22', 'Param'),
('电子膨胀阀开度-U22', 'eevpos_u22', 'Param'),
('高压压力-U22', 'highpress_u22', 'Param'),
('送风温度-U22', 'sas_u22', 'Param'),
('通风机电流-U11', 'I_EF_u11', 'Param'),
('通风机电流-U12', 'I_EF_u12', 'Param'),
('冷凝风机电流-U11', 'I_CF_u11', 'Param'),
('冷凝风机电流-U12', 'I_CF_u12', 'Param'),
('通风机电流-U21', 'I_EF_u21', 'Param'),
('通风机电流-U22', 'I_EF_u22', 'Param'),
('冷凝风机电流-U21', 'I_CF_u21', 'Param'),
('冷凝风机电流-U22', 'I_CF_u22', 'Param'),
('总电流-机组1', 'I_HVAC_u1', 'Param'),
('总电流-机组2', 'I_HVAC_u2', 'Param'),
('空调机组能耗', 'dwPower', 'Param'),
('紧急逆变器累计运行时间', 'dwemerg_op_tm', 'Statistics'),
('紧急逆变器累计运行次数', 'dwemerg_op_cnt', 'Statistics'),
('通风机累计运行时间-U1-1', 'dwEF_op_tm_u11', 'Statistics'),
('冷凝风机累计运行时间-U1-1', 'dwCF_op_tm_u11', 'Statistics'),
('冷凝风机累计运行时间-U1-2', 'dwCF_op_tm_u12', 'Statistics'),
('压缩机累计运行时间-U11', 'dwCP_op_tm_u11', 'Statistics'),
('压缩机累计运行时间-U12', 'dwCP_op_tm_u12', 'Statistics'),
('空气净化器累计运行时间-U1-1', 'dwAP_op_tm_u11', 'Statistics'),
('空气净化器累计运行时间-U1-2', 'dwAP_op_tm_u12', 'Statistics'),
('新风阀开关次数-U1', 'dwFAD_op_cnt_u1', 'Statistics'),
('回风阀开关次数-U1', 'dwRAD_op_cnt_u1', 'Statistics'),
('通风机累计开关次数-U1-1', 'dwEF_op_cnt_u11', 'Statistics'),
('冷凝风机累计开关次数-U1-1', 'dwCF_op_cnt_u11', 'Statistics'),
('冷凝风机累计开关次数-U1-2', 'dwCF_op_cnt_u12', 'Statistics'),
('压缩机累计开关次数-U11', 'dwCP_op_cnt_u11', 'Statistics'),
('压缩机累计开关次数-U12', 'dwCP_op_cnt_u12', 'Statistics'),
('空气净化器累计开关次数-U1-1', 'dwAP_op_cnt_u11', 'Statistics'),
('空气净化器累计开关次数-U1-2', 'dwAP_op_cnt_u12', 'Statistics'),
('通风机累计运行时间-U2-1', 'dwEF_op_tm_u21', 'Statistics'),
('冷凝风机累计运行时间-U2-1', 'dwCF_op_tm_u21', 'Statistics'),
('冷凝风机累计运行时间-U2-2', 'dwCF_op_tm_u22', 'Statistics'),
('压缩机累计运行时间-U2-1', 'dwCP_op_tm_u21', 'Statistics'),
('压缩机累计运行时间-U2-2', 'dwCP_op_tm_u22', 'Statistics'),
('空气净化器累计运行时间-U2-1', 'dwAP_op_tm_u21', 'Statistics'),
('空气净化器累计运行时间-U2-2', 'dwAP_op_tm_u22', 'Statistics'),
('新风阀开关次数-U2', 'dwFAD_op_cnt_u2', 'Statistics'),
('回风阀开关次数-U2', 'dwRAD_op_cnt_u2', 'Statistics'),
('通风机累计开关次数-U2-1', 'dwEF_op_cnt_u21', 'Statistics'),
('冷凝风机累计开关次数-U2-1', 'dwCF_op_cnt_u21', 'Statistics'),
('冷凝风机累计开关次数-U2-2', 'dwCF_op_cnt_u22', 'Statistics'),
('压缩机累计开关次数-U2-1', 'dwCP_op_cnt_u21', 'Statistics'),
('压缩机累计开关次数-U2-2', 'dwCP_op_cnt_u22', 'Statistics'),
('空气净化器累计开关次数-U2-1', 'dwAP_op_cnt_u21', 'Statistics'),
('空气净化器累计开关次数-U2-2', 'dwAP_op_cnt_u22', 'Statistics');

-- 插入数据
INSERT INTO sys_fields (field_name, field_code, field_category) VALUES
('冷媒泄露预警 U-11', 'ref_leak_u11', 'predict'),
('冷媒泄露预警 U-12', 'ref_leak_u12', 'predict'),
('冷媒泄露预警 U-21', 'ref_leak_u21', 'predict'),
('冷媒泄露预警 U-22', 'ref_leak_u22', 'predict'),
('制冷系统预警 U-1', 'f_cp_u1', 'predict'),
('制冷系统预警 U-2', 'f_cp_u2', 'predict'),
('新风温度传感器预警', 'f_fas', 'predict'),
('回风温度传感器预警', 'f_ras', 'predict'),
('车厢温度超温预警', 'cabin_overtemp', 'predict'),
('滤网脏堵预警 U-1', 'f_presdiff_u1', 'predict'),
('滤网脏堵预警 U-2', 'f_presdiff_u2', 'predict'),
('通风机电流预警 U-11', 'f_ef_u11', 'predict'),
('通风机电流预警 U-12', 'f_ef_u12', 'predict'),
('通风机电流预警 U-21', 'f_ef_u21', 'predict'),
('通风机电流预警 U-22', 'f_ef_u22', 'predict'),
('冷凝风机电流预警 U-11', 'f_cf_u11', 'predict'),
('冷凝风机电流预警 U-12', 'f_cf_u12', 'predict'),
('冷凝风机电流预警 U-21', 'f_cf_u21', 'predict'),
('冷凝风机电流预警 U-22', 'f_cf_u22', 'predict'),
('压缩机电流预警 U-11', 'f_fas_u11', 'predict'),
('压缩机电流预警 U-12', 'f_fas_u12', 'predict'),
('压缩机电流预警 U-21', 'f_fas_u21', 'predict'),
('压缩机电流预警 U-22', 'f_fas_u22', 'predict'),
('空气质量监测终端预警 U-1', 'f_aq_u1', 'predict'),
('空气质量监测终端预警 U-2', 'f_aq_u2', 'predict');

-- 将field_code字段全部转换为小写
UPDATE sys_fields
SET field_code = LOWER(field_code);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_sys_fields_field_code ON sys_fields(field_code);