CREATE OR REPLACE VIEW public.vw_train_warning_info
 AS
 SELECT max(pro_predict.msg_calc_train_no) AS train_no,
    pro_predict.msg_calc_dvc_no AS carriage_no,
    last(pro_predict.msg_calc_dvc_time, pro_predict.msg_calc_dvc_time) AS warning_time,
    last(pro_predict.ref_leak_u11, pro_predict.msg_calc_dvc_time) AS ref_leak_u11,
    last(pro_predict.ref_leak_u12, pro_predict.msg_calc_dvc_time) AS ref_leak_u12,
    last(pro_predict.ref_leak_u21, pro_predict.msg_calc_dvc_time) AS ref_leak_u21,
    last(pro_predict.ref_leak_u22, pro_predict.msg_calc_dvc_time) AS ref_leak_u22,
    last(pro_predict.f_cp_u1, pro_predict.msg_calc_dvc_time) AS f_cp_u1,
    last(pro_predict.f_cp_u2, pro_predict.msg_calc_dvc_time) AS f_cp_u2
    last(pro_predict.f_fas, pro_predict.msg_calc_dvc_time) AS f_fas,
    last(pro_predict.f_ras, pro_predict.msg_calc_dvc_time) AS f_ras,
    last(pro_predict.cabin_overtemp, pro_predict.msg_calc_dvc_time) AS cabin_overtemp,
    last(pro_predict.f_presdiff_u1, pro_predict.msg_calc_dvc_time) AS f_presdiff_u1,
    last(pro_predict.f_presdiff_u2, pro_predict.msg_calc_dvc_time) AS f_presdiff_u2,
    last(pro_predict.f_ef_u11, pro_predict.msg_calc_dvc_time) AS f_ef_u11,
    last(pro_predict.f_ef_u12, pro_predict.msg_calc_dvc_time) AS f_ef_u12,
    last(pro_predict.f_ef_u21, pro_predict.msg_calc_dvc_time) AS f_ef_u21,
    last(pro_predict.f_ef_u22, pro_predict.msg_calc_dvc_time) AS f_ef_u22,
    last(pro_predict.f_cf_u11, pro_predict.msg_calc_dvc_time) AS f_cf_u11,
    last(pro_predict.f_cf_u12, pro_predict.msg_calc_dvc_time) AS f_cf_u12,
    last(pro_predict.f_cf_u21, pro_predict.msg_calc_dvc_time) AS f_cf_u21,
    last(pro_predict.f_cf_u22, pro_predict.msg_calc_dvc_time) AS f_cf_u22,
    last(pro_predict.f_exufan, pro_predict.msg_calc_dvc_time) AS f_exufan,
    last(pro_predict.f_fas_u11, pro_predict.msg_calc_dvc_time) AS f_fas_u11,
    last(pro_predict.f_fas_u12, pro_predict.msg_calc_dvc_time) AS f_fas_u12,
    last(pro_predict.f_fas_u21, pro_predict.msg_calc_dvc_time) AS f_fas_u21,
    last(pro_predict.f_fas_u22, pro_predict.msg_calc_dvc_time) AS f_fas_u22,
    last(pro_predict.f_aq_u1, pro_predict.msg_calc_dvc_time) AS f_aq_u1,
    last(pro_predict.f_aq_u2, pro_predict.msg_calc_dvc_time) AS f_aq_u2,
    '机组1-系统1冷媒泄漏预警'::text AS ref_leak_u11_name,
    '机组1-系统2冷媒泄漏预警'::text AS ref_leak_u12_name,
    '机组2-系统1冷媒泄漏预警'::text AS ref_leak_u21_name,
    '机组2-系统2冷媒泄漏预警'::text AS ref_leak_u22_name,
    '机组1-制冷系统预警'::text AS f_cp_u1_name,
    '机组2-制冷系统预警'::text AS f_cp_u2_name,
    '新风温度传感器预警'::text AS f_fas_name,
    '回风温度传感器预警'::text AS f_ras_name,
    '车厢温度超温预警'::text AS cabin_overtemp_name,
    '机组1-滤网脏堵预警'::text AS f_presdiff_u1_name,
    '机组2-滤网脏堵预警'::text AS f_presdiff_u2_name,
    '机组1-通风机1电流预警'::text AS f_ef_u11_name,
    '机组1-通风机2电流预警'::text AS f_ef_u12_name,
    '机组2-通风机1电流预警'::text AS f_ef_u21_name,
    '机组2-通风机2电流预警'::text AS f_ef_u22_name,
    '机组1-冷凝风机1电流预警'::text AS f_cf_u11_name,
    '机组1-冷凝风机2电流预警'::text AS f_cf_u12_name,
    '机组2-冷凝风机1电流预警'::text AS f_cf_u21_name,
    '机组2-冷凝风机2电流预警'::text AS f_cf_u22_name,
    '废排风机电流预警'::text AS f_exufan_name,
    '机组1-压缩机1电流预警'::text AS f_fas_u11_name,
    '机组1-压缩机2电流预警'::text AS f_fas_u12_name,
    '机组2-压缩机1电流预警'::text AS f_fas_u21_name,
    '机组2-压缩机2电流预警'::text AS f_fas_u22_name,
    '机组1-空气质量预警'::text AS f_aq_u1_name,
    '机组2-空气质量预警'::text AS f_aq_u2_name
   FROM pro_predict
  WHERE pro_predict.msg_calc_dvc_time >= (now() - '2 minute'::interval) AND pro_predict.msg_calc_train_no <> '00000'::text
  GROUP BY pro_predict.msg_calc_dvc_no;