CREATE MATERIALIZED VIEW  public.vw_alarm_info_all_date
WITH (timescaledb.continuous, timescaledb.materialized_only=true) AS
 SELECT max(dev_macda.msg_calc_train_no) AS train_no,
    max(dev_macda.msg_calc_dvc_no) AS carriage_no,
	time_bucket('1 day', dev_macda.msg_calc_parse_time) AS alarm_time,
    max(dev_macda.bocflt_ef_u11) AS bocflt_ef_u11,
    max(dev_macda.bocflt_ef_u12) AS bocflt_ef_u12,
    max(dev_macda.bocflt_cf_u11) AS bocflt_cf_u11,
    max(dev_macda.bocflt_cf_u12) AS bocflt_cf_u12,
    max(dev_macda.bflt_vfd_u11) AS bflt_vfd_u11,
    max(dev_macda.bflt_vfd_com_u11) AS bflt_vfd_com_u11,
    max(dev_macda.bflt_vfd_u12) AS bflt_vfd_u12,
    max(dev_macda.bflt_vfd_com_u12) AS bflt_vfd_com_u12,
    max(dev_macda.blpflt_comp_u11) AS blpflt_comp_u11,
    max(dev_macda.bscflt_comp_u11) AS bscflt_comp_u11,
    max(dev_macda.bscflt_vent_u11) AS bscflt_vent_u11,
    max(dev_macda.blpflt_comp_u12) AS blpflt_comp_u12,
    max(dev_macda.bscflt_comp_u12) AS bscflt_comp_u12,
    max(dev_macda.bscflt_vent_u12) AS bscflt_vent_u12,
    max(dev_macda.bflt_fad_u11) AS bflt_fad_u11,
    max(dev_macda.bflt_fad_u12) AS bflt_fad_u12,
    max(dev_macda.bflt_rad_u11) AS bflt_rad_u11,
    max(dev_macda.bflt_rad_u12) AS bflt_rad_u12,
    max(dev_macda.bflt_ap_u11) AS bflt_ap_u11,
    max(dev_macda.bflt_expboard_u1) AS bflt_expboard_u1,
    max(dev_macda.bflt_frstemp_u1) AS bflt_frstemp_u1,
    max(dev_macda.bflt_rnttemp_u1) AS bflt_rnttemp_u1,
    max(dev_macda.bflt_splytemp_u11) AS bflt_splytemp_u11,
    max(dev_macda.bflt_splytemp_u12) AS bflt_splytemp_u12,
    max(dev_macda.bflt_coiltemp_u11) AS bflt_coiltemp_u11,
    max(dev_macda.bflt_coiltemp_u12) AS bflt_coiltemp_u12,
    max(dev_macda.bflt_insptemp_u11) AS bflt_insptemp_u11,
    max(dev_macda.bflt_insptemp_u12) AS bflt_insptemp_u12,
    max(dev_macda.bflt_lowpres_u11) AS bflt_lowpres_u11,
    max(dev_macda.bflt_lowpres_u12) AS bflt_lowpres_u12,
    max(dev_macda.bflt_highpres_u11) AS bflt_highpres_u11,
    max(dev_macda.bflt_highpres_u12) AS bflt_highpres_u12,
    max(dev_macda.bflt_diffpres_u1) AS bflt_diffpres_u1,
    max(dev_macda.bocflt_ef_u21) AS bocflt_ef_u21,
    max(dev_macda.bocflt_ef_u22) AS bocflt_ef_u22,
    max(dev_macda.bocflt_cf_u21) AS bocflt_cf_u21,
    max(dev_macda.bocflt_cf_u22) AS bocflt_cf_u22,
    max(dev_macda.bflt_vfd_u21) AS bflt_vfd_u21,
    max(dev_macda.bflt_vfd_com_u21) AS bflt_vfd_com_u21,
    max(dev_macda.bflt_vfd_u22) AS bflt_vfd_u22,
    max(dev_macda.bflt_vfd_com_u22) AS bflt_vfd_com_u22,
    max(dev_macda.blpflt_comp_u21) AS blpflt_comp_u21,
    max(dev_macda.bscflt_comp_u21) AS bscflt_comp_u21,
    max(dev_macda.bscflt_vent_u21) AS bscflt_vent_u21,
    max(dev_macda.blpflt_comp_u22) AS blpflt_comp_u22,
    max(dev_macda.bscflt_comp_u22) AS bscflt_comp_u22,
    max(dev_macda.bscflt_vent_u22) AS bscflt_vent_u22,
    max(dev_macda.bflt_fad_u21) AS bflt_fad_u21,
    max(dev_macda.bflt_fad_u22) AS bflt_fad_u22,
    max(dev_macda.bflt_rad_u21) AS bflt_rad_u21,
    max(dev_macda.bflt_rad_u22) AS bflt_rad_u22,
    max(dev_macda.bflt_ap_u21) AS bflt_ap_u21,
    max(dev_macda.bflt_expboard_u2) AS bflt_expboard_u2,
    max(dev_macda.bflt_frstemp_u2) AS bflt_frstemp_u2,
    max(dev_macda.bflt_rnttemp_u2) AS bflt_rnttemp_u2,
    max(dev_macda.bflt_splytemp_u21) AS bflt_splytemp_u21,
    max(dev_macda.bflt_splytemp_u22) AS bflt_splytemp_u22,
    max(dev_macda.bflt_coiltemp_u21) AS bflt_coiltemp_u21,
    max(dev_macda.bflt_coiltemp_u22) AS bflt_coiltemp_u22,
    max(dev_macda.bflt_insptemp_u21) AS bflt_insptemp_u21,
    max(dev_macda.bflt_insptemp_u22) AS bflt_insptemp_u22,
    max(dev_macda.bflt_lowpres_u21) AS bflt_lowpres_u21,
    max(dev_macda.bflt_lowpres_u22) AS bflt_lowpres_u22,
    max(dev_macda.bflt_highpres_u21) AS bflt_highpres_u21,
    max(dev_macda.bflt_highpres_u22) AS bflt_highpres_u22,
    max(dev_macda.bflt_diffpres_u2) AS bflt_diffpres_u2,
    max(dev_macda.bflt_emergivt) AS bflt_emergivt,
    max(dev_macda.bflt_vehtemp_u1) AS bflt_vehtemp_u1,
    max(dev_macda.bflt_vehtemp_u2) AS bflt_vehtemp_u2,
    max(dev_macda.bflt_airmon_u1) AS bflt_airmon_u1,
    max(dev_macda.bflt_airmon_u2) AS bflt_airmon_u2,
    max(dev_macda.bflt_currentmon) AS bflt_currentmon,
    max(dev_macda.bflt_tcms) AS bflt_tcms,
    max(dev_macda.bflt_tempover) AS bflt_tempover,
    max(dev_macda.bflt_powersupply_u1) AS bflt_powersupply_u1,
    max(dev_macda.bflt_powersupply_u2) AS bflt_powersupply_u2,
    max(dev_macda.bflt_exhaustfan) AS bflt_exhaustfan,
    max(dev_macda.bflt_exhaustval) AS bflt_exhaustval
   FROM dev_macda
   where dev_macda.msg_calc_parse_time >= (now() - '2.2 day'::interval)
  GROUP BY alarm_time, dev_macda.msg_calc_train_no;


  SELECT add_continuous_aggregate_policy('vw_alarm_info_all_date'::regclass, start_offset=>'2.1 day'::interval, end_offset=>'1 hour'::interval,  schedule_interval=>'2 hour'::interval);
